import{a as S,S as v,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function c(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=c(t);fetch(t.href,o)}})();const w="52368753-eba0a00d68a5190bbbbc4e7af",q="https://pixabay.com/api/",p=15;async function P(r,e){const c={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:p},{data:i}=await S.get(q,{params:c});return i}const y=document.querySelector(".loader"),m=document.querySelector(".gallery"),a=document.querySelector(".load-more-btn"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function A(r){const e=r.map(({webformatURL:c,largeImageURL:i,tags:t,likes:o,views:u,comments:b,downloads:L})=>`<li class="gallery-item">
        <a class="gallery-link" href="${i}">
        <img class="img-item" src="${c}" alt="${t}"/>
        </a>
        <p>Likes <span>${o}</span></p>
        <p>View <span>${u}</span></p>
        <p>Comments <span>${b}</span></p>
        <p>Downloads <span>${L}</span></p>
        </li>`).join("");m.insertAdjacentHTML("beforeend",e),R.refresh()}function $(){m.innerHTML=""}function B(){y.classList.add("is-visible")}function E(){y.classList.remove("is-visible")}function M(){a&&(a.classList.add("is-visible"),a.style.display="block")}function l(){a&&(a.classList.remove("is-visible"),a.style.display="none")}const I=document.querySelector(".form"),O=document.querySelector('[name="search-text"]'),f=document.querySelector(".load-more-btn"),x=document.querySelector(".gallery");let h="",s=1,d=0;l();function _(){const r=x.querySelector(".gallery-item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}async function g({doScroll:r=!1}={}){B(),f.disabled=!0;try{const e=await P(h,s);if(!Array.isArray(e.hits)||e.hits.length===0){s===1?n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l();return}A(e.hits),s===1&&(d=Math.ceil(e.totalHits/p)),s<d?(M(),f.disabled=!1):(l(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),s+=1,r&&_()}catch(e){console.error(e),l(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{E(),f.disabled=!1}}I.addEventListener("submit",async r=>{r.preventDefault();const e=O.value.trim();if(!e){n.warning({title:"Caution",message:"Please type something to search.",position:"topRight"});return}h=e,s=1,d=0,$(),l(),await g({doScroll:!1})});f.addEventListener("click",async()=>{if(d&&s>d){l(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}await g({doScroll:!0})});
//# sourceMappingURL=index.js.map
