import{a as w,S as q,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const P="52368753-eba0a00d68a5190bbbbc4e7af",A="https://pixabay.com/api/",f=15;async function p(t,r){const o={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:f},{data:i}=await w.get(A,{params:o});return i}const y=document.querySelector(".loader"),m=document.querySelector(".gallery"),l=document.querySelector(".load-more-btn"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const r=t.map(({webformatURL:o,largeImageURL:i,tags:e,likes:s,views:c,comments:v,downloads:S})=>`<li class="gallery-item">
        <a class="gallery-link" href="${i}">
        <img class="img-item" src="${o}" alt="${e}"/>
        </a>
        <p>Likes <span>${s}</span></p>
        <p>View <span>${c}</span></p>
        <p>Comments <span>${v}</span></p>
        <p>Downloads <span>${S}</span></p>
        </li>`).join("");m.insertAdjacentHTML("beforeend",r),E.refresh()}function R(){m.innerHTML=""}function g(){y.classList.add("is-visible")}function b(){y.classList.remove("is-visible")}function L(){l&&(l.classList.add("is-visible"),l.style.display="block")}function u(){l&&(l.classList.remove("is-visible"),l.style.display="none")}document.querySelector(".gallery");const M=document.querySelector(".form"),B=document.querySelector('[name="search-text"]');document.querySelector(".loader");const $=document.querySelector(".load-more-btn");let d="",a=1;u();function I(){var o;const t=(o=document.querySelector(".gallery"))==null?void 0:o.firstElementChild;if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}M.addEventListener("submit",async t=>{t.preventDefault();const r=B.value.trim();if(!r){n.warning({title:"Caution",message:"Please type something to search.",position:"topRight"});return}d=r,a=1,R(),u(),g();try{const o=await p(d,a);if(!Array.isArray(o.hits)||o.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(o.hits);const i=Math.ceil(o.totalHits/f);a<i?L():(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),a+=1}catch(o){console.error(o),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});$.addEventListener("click",async()=>{u(),g();try{const t=await p(d,a);if(!Array.isArray(t.hits)||t.hits.length===0){n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}h(t.hits),I();const r=Math.ceil(t.totalHits/f);a<r?L():(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),a+=1}catch(t){console.error(t),n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
